### ISSUE TITLE
Maybe the Nextflow problem

### ISSUE THREAD

**Issue by sam-mic** [sanger-bentley-group/GBS-Typer-sanger-nf#80]
Hi,

I tried to install the nextflow with conda and git clone the project
------
I run an example with the recommend  command and encountered an error. I'm not familiar with nextflow and could anyone help me with it? Thanks. The following is the error message:
------
 N E X T F L O W  ~  version 19.01.0
Launching ../main.nf [festering_lumiere] - revision: 90e74631b4
ERROR ~ The current scope already contains a variable of the name it
 @ line 215, column 47.
   alleles.out.new_pbp.subscribe { it ->
                                 ^

_nf_script_49bbb228: 238: The current scope already contains a variable of the name it
 @ line 238, column 47.
   alleles.out.new_pbp.subscribe { it ->
                                 ^

_nf_script_49bbb228: 261: The current scope already contains a variable of the name it
 @ line 261, column 47.
   alleles.out.new_pbp.subscribe { it ->
                                 ^

_nf_script_49bbb228: 322: The current scope already contains a variable of the name it
 @ line 322, column 44.
   LST.out.new_alleles.subscribe { it ->
                                 ^

_nf_script_49bbb228: 325: The current scope already contains a variable of the name it
 @ line 325, column 39.
               MLST.out.pileup.subscribe { it ->
                                         ^

5 errors

**Comment by blue-moon22** [comment]
Hi there,

Apologies for the delayed response. Which directory are you running this in? It seems like you're launching it within another directory. Try running it again in the `GPS-Typer-sanger-nf` directory itself (but using the path `main.nf` etc..)
