### ISSUE TITLE
Advice for HPC with slurm

### ISSUE THREAD

**Issue by Tetrajf** [sanger-bentley-group/GBS-Typer-sanger-nf#91]
To Whom it May Concern

I'm working on a HPC with singularity but not the Sanger farm. I was wondering if you have any advice on how to create a nextflow.config file to use singularity with slurm. Sorry this may be a basic question... I have pulled the docker container as: bluemoon222-gbs-typer-sanger-nf-0.0.7.img and have tried to point the process container to this image but I get the error stating that it cannot find srst2. 

Kind Regards
Tetra

**Comment by HarryHung** [comment]
Hi Tetra, sorry for the delayed response. I would suggest looking into this part of the Nextflow documentation: https://www.nextflow.io/docs/stable/executor.html#slurm, or talk to people in your institute that are using any Nextflow pipeline on your SLURM-based HPC.
